spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/eickrono_autenticacao
    username: eickrono
    password: senhaSuperSeguraDev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: autenticacao_dev
  flyway:
    schemas: autenticacao_dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/eickrono
          jwk-set-uri: http://127.0.0.1:8080/realms/eickrono/protocol/openid-connect/certs

seguranca:
  cors:
    origens-permitidas:
      - http://localhost:3000
      - http://127.0.0.1:3000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

documentacao:
  swagger:
    usuario: swagger
    senha: swagger-dev

logging:
  level:
    com.eickrono.api.identidade: INFO

identidade:
  seguranca:
    app:
      modo-observacao: true
  atestacao:
    app:
      permitir-validacao-local-sem-provedor-oficial: ${IDENTIDADE_ATESTACAO_APP_PERMITIR_VALIDACAO_LOCAL_SEM_PROVEDOR_OFICIAL:true}
      google:
        habilitado: ${IDENTIDADE_ATESTACAO_APP_GOOGLE_HABILITADO:false}
      apple:
        habilitado: ${IDENTIDADE_ATESTACAO_APP_APPLE_HABILITADO:false}
  cadastro:
    interna:
      keycloak:
        url-base: ${IDENTIDADE_CADASTRO_INTERNO_KEYCLOAK_URL_BASE:http://localhost:8080}
        realm: ${IDENTIDADE_CADASTRO_INTERNO_KEYCLOAK_REALM:eickrono}
        client-id: ${IDENTIDADE_CADASTRO_INTERNO_KEYCLOAK_CLIENT_ID:admin-cli}
  sessao:
    interna:
      keycloak:
        url-base: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_URL_BASE:http://localhost:8080}
        realm: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_REALM:eickrono}
        client-id: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_CLIENT_ID:app-flutter-local}
        scope: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_SCOPE:openid identidade:ler vinculos:ler vinculos:escrever offline_access}
        token-exchange-client-id: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_TOKEN_EXCHANGE_CLIENT_ID:eickrono-autenticacao-interno}
        token-exchange-client-secret: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_TOKEN_EXCHANGE_CLIENT_SECRET:${INTEGRACAO_PERFIL_JWT_INTERNO_CLIENT_SECRET:}}
        token-exchange-audience: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_TOKEN_EXCHANGE_AUDIENCE:app-flutter-local}
        token-exchange-scope: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_TOKEN_EXCHANGE_SCOPE:openid identidade:ler vinculos:ler vinculos:escrever offline_access}
  social:
    credenciais:
      apple:
        audiences: ${IDENTIDADE_SOCIAL_CREDENCIAIS_APPLE_AUDIENCES:com.eickrono.thimisu}
  dispositivo:
    token:
      segredo-hmac: ${IDENTIDADE_DEVICE_TOKEN_SECRET:dev-device-token-secret}
    codigo:
      segredo-hmac: ${IDENTIDADE_CODIGO_TOKEN_SECRET:dev-codigo-secret}
