spring:
  config:
    activate:
      on-profile: hml
  datasource:
    url: jdbc:postgresql://banco-postgres:5432/eickrono_identidade_hml
    username: eickrono_hml
    password: senhaSuperSeguraHml
  flyway:
    schemas: identidade_hml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://hml-identidade.eickrono.com.br/realms/eickrono
          jwk-set-uri: https://hml-identidade.eickrono.com.br/realms/eickrono/protocol/openid-connect/certs

seguranca:
  mtls:
    habilitado: true
    keystore-arquivo: classpath:certificados/hml-servidor.p12
    keystore-senha: senhaCertificadoHml
    truststore-arquivo: classpath:certificados/hml-truststore.p12
    truststore-senha: senhaTruststoreHml
  cors:
    origens-permitidas:
      - https://hml-app.eickrono.com.br

documentacao:
  swagger:
    usuario: swagger
    senha: Sw9@Qm2!Tx7#Lp4$Vz8Kr
    ips-permitidos:
      - 10.0.0.10
      - 10.0.0.11

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.eickrono.api.identidade: INFO

identidade:
  seguranca:
    app:
      modo-observacao: true
  atestacao:
    app:
      permitir-validacao-local-sem-provedor-oficial: ${IDENTIDADE_ATESTACAO_APP_PERMITIR_VALIDACAO_LOCAL_SEM_PROVEDOR_OFICIAL:true}
      google:
        habilitado: ${IDENTIDADE_ATESTACAO_APP_GOOGLE_HABILITADO:false}
      apple:
        habilitado: ${IDENTIDADE_ATESTACAO_APP_APPLE_HABILITADO:false}
  cadastro:
    interna:
      keycloak:
        url-base: ${IDENTIDADE_CADASTRO_INTERNO_KEYCLOAK_URL_BASE:http://localhost:18080}
        realm: ${IDENTIDADE_CADASTRO_INTERNO_KEYCLOAK_REALM:eickrono}
  sessao:
    interna:
      keycloak:
        url-base: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_URL_BASE:http://localhost:18080}
        realm: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_REALM:eickrono}
        client-id: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_CLIENT_ID:app-flutter-hml}
        token-exchange-client-id: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_TOKEN_EXCHANGE_CLIENT_ID:eickrono-autenticacao-interno}
        token-exchange-client-secret: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_TOKEN_EXCHANGE_CLIENT_SECRET:${INTEGRACAO_PERFIL_JWT_INTERNO_CLIENT_SECRET:}}
        token-exchange-audience: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_TOKEN_EXCHANGE_AUDIENCE:app-flutter-hml}
        token-exchange-scope: ${IDENTIDADE_SESSAO_INTERNA_KEYCLOAK_TOKEN_EXCHANGE_SCOPE:openid identidade:ler vinculos:ler vinculos:escrever offline_access}
  social:
    credenciais:
      apple:
        audiences: ${IDENTIDADE_SOCIAL_CREDENCIAIS_APPLE_AUDIENCES:com.eickrono.thimisu}
  dispositivo:
    token:
      segredo-hmac: ${IDENTIDADE_DEVICE_TOKEN_SECRET}
    codigo:
      segredo-hmac: ${IDENTIDADE_CODIGO_TOKEN_SECRET}
