<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 config/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.eickrono</groupId>
    <artifactId>eickrono-autenticacao-servidor</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Eickrono Autenticacao Servidor</name>
    <description>Customizacoes do Keycloak e orquestracao local do ecossistema de autenticacao da Eickrono.</description>

    <modules>
        <module>modulos/modulo-eickrono-keycloak</module>
        <module>modulos/modulo-eickrono-autenticacao</module>
    </modules>

</project>
