spring:
  application:
    name: api-contas-eickrono
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  cache:
    type: caffeine
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8082

seguranca:
  cors:
    origens-permitidas:
      - http://localhost:3001
  mtls:
    habilitado: false

fapi:
  seguranca:
    audiencia-esperada: api-contas-eickrono
    tolerancia-clock-skew-segundos: 60

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

documentacao:
  swagger:
    usuario: swagger
    senha: swagger
    ips-permitidos:
      - 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: api-contas-eickrono

logging:
  level:
    root: INFO
    com.eickrono.api.contas: INFO
