ALTER TABLE cadastros_conta
    ADD COLUMN IF NOT EXISTS usuario_id_perfil VARCHAR(36),
    ADD COLUMN IF NOT EXISTS tipo_pessoa VARCHAR(16) NOT NULL DEFAULT 'FISICA',
    ADD COLUMN IF NOT EXISTS nome_fantasia VARCHAR(255),
    ADD COLUMN IF NOT EXISTS usuario VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS sexo VARCHAR(16),
    ADD COLUMN IF NOT EXISTS pais_nascimento VARCHAR(8),
    ADD COLUMN IF NOT EXISTS data_nascimento DATE;
