CREATE SCHEMA IF NOT EXISTS catalogo;

CREATE SCHEMA IF NOT EXISTS autenticacao;

CREATE SCHEMA IF NOT EXISTS dispositivos;

CREATE SCHEMA IF NOT EXISTS seguranca;

CREATE SCHEMA IF NOT EXISTS auditoria;
