FROM quay.io/keycloak/keycloak:26.5.5

USER root

COPY modulos/modulo-eickrono-keycloak/target/modulo-eickrono-keycloak-*.jar /opt/keycloak/providers/modulo-eickrono-keycloak.jar
COPY autorizacao/realms /opt/keycloak/import-source
COPY autorizacao/temas/login-ptbr /opt/keycloak/themes/login-ptbr
COPY autorizacao/providers/configuracoes-fapi /opt/keycloak/providers/configuracoes-fapi
COPY autorizacao/providers/mapeamentos-atributos /opt/keycloak/providers/mapeamentos-atributos
COPY autorizacao/providers/scripts-spi /opt/keycloak/providers/scripts-spi
COPY infraestrutura/prod/docker/start-keycloak-hml.sh /opt/keycloak/bin/start-keycloak-hml.sh

RUN chmod +x /opt/keycloak/bin/start-keycloak-hml.sh /opt/keycloak/import-source/render-realms.sh \
    && chown -R keycloak:keycloak /opt/keycloak/providers /opt/keycloak/import-source /opt/keycloak/themes /opt/keycloak/bin/start-keycloak-hml.sh

USER keycloak

EXPOSE 8080

ENTRYPOINT ["/opt/keycloak/bin/start-keycloak-hml.sh"]
